export default [
  { id: 1, text: 'FAQ' },
  { id: 2, text: 'Help Centre' },
  { id: 3, text: 'Account' },
  { id: 4, text: 'Media Centre' },
  { id: 5, text: 'Investor relations' },
  { id: 6, text: 'Jobs' },
  { id: 7, text: 'Redeem gift cards' },
  { id: 8, text: 'Buy gift cards' },
  { id: 9, text: 'Ways to watch' },
  { id: 10, text: 'Terms of Use' },
  { id: 11, text: 'Privacy' },
  { id: 12, text: 'Cookie preferences' },
  { id: 13, text: 'Corporate information' },
  { id: 14, text: 'Contact us' },
  { id: 15, text: 'Speed test' },
  { id: 16, text: 'Legal notices' },
  { id: 17, text: 'Hotflix Originals' },
];
